name: verman_example
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+9

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.0
  firebase_core: ^3.9.0
  # flutter_google_places: ^0.3.0
  flutter_riverpod: ^2.6.1
  top_snackbar_flutter: ^3.1.0
  firebase_messaging: ^15.1.6
  loader_overlay: ^5.0.0
  image_picker: ^1.1.2

  # google_maps_flutter: ^2.2.6

  intl: ^0.20.2
  flutter_rating_bar: ^4.0.1
  # sqflite: ^2.4.1
  # path: ^1.8.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.4.4
  dio: ^5.4.3+1
  google_sign_in: ^6.2.2
  flutter_svg: ^2.0.9
  pinput: ^5.0.0
  flutter_easyloading: ^3.0.5
  validatorless: ^1.2.4
  sliver_tools: ^0.2.12
  flutter_staggered_grid_view: ^0.7.0
  iconify_flutter: ^0.0.7
  riverpod_annotation: ^2.6.1
  shimmer: ^3.0.0
  # flutter_secure_storage: ^9.2.4
  hive_ce: ^2.10.1
  fl_chart: ^0.70.2
  gif_view: ^1.0.2
  google_fonts: ^6.1.0
  hive_ce_flutter: ^2.2.0
  webview_flutter: ^4.10.0
  lottie: ^3.3.1
  uuid: ^4.5.1
  sizer: ^3.0.5
  google_maps_flutter: ^2.12.2
  widget_to_marker: ^1.0.6
  location_autocomplete: ^0.0.2
  reactive_forms: ^18.0.0
  geolocator: ^14.0.1
  mobile_scanner: ^7.0.1
  flutter_custom_tabs: ^2.4.0
  app_links: ^6.4.0
  smooth_page_indicator: ^1.2.1
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.2
  currency_formatter: ^2.3.0
  so_money:
    git:
      url: https://github.com/artkinx/so_money.git
      ref: f6000a3
  board_datetime_picker: ^2.8.1
  flutter_image_compress: ^2.4.0
  mime: ^1.0.4
  http_parser: ^4.0.2
  internet_connection_checker: ^3.0.1
  staggered_grid_view: ^0.0.1
  chewie: ^1.13.0
  video_player: ^2.10.0
  animate_do: ^4.2.0
  visibility_detector: ^0.4.0+2
  # table_calendar: ^3.2.0
  # file_selector: ^1.0.3

dependency_overrides:
  package_info_plus: ^8.1.2
  google_api_headers: ^4.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0
  build_runner: ^2.1.4
  riverpod_generator: ^2.6.4
  hive_ce_generator: ^1.0.1
  verman:
    path: ../../verman

flutter:
  uses-material-design: true


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo/launcher.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/logo/launcher.png"
  background_color_ios: "#000000"
  image_path_ios_dark_transparent: "assets/images/logo/launcher.png"


verman_config:
  # path: verman.yaml
  ios: ios/runner/info.plist
  android: android/app/src/build.gradle.kts