name: verman_example
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.1+11

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  verman:
    path: ../

flutter:
  uses-material-design: true


verman_config:
  # path: verman.yaml
  ios: ios/runner/info.plist
  android: android/app/src/build.gradle.kts